# Generated by Django 5.0.6 on 2024-05-14 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_author',
            new_name='BookAuthor',
        ),
        migrations.RenameModel(
            old_name='BookCategory',
            new_name='CategoryBooks',
        ),
        migrations.AddField(
            model_name='books',
            name='created_at',
            field=models.DateField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='updated_at',
            field=models.DateField(default='exit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='book_lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.language'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(default='default_img/default_book_img.png', upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
