# Generated by Django 5.0.6 on 2024-05-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_book_author_bookauthor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='books',
            name='updated_at',
        ),
    ]
